const data = {
  products: [
    {
      _id: '1',
      name: 'Asian Snuff Bottle',
      slug: 'Snuff Bottle',
      category: 'Asian',
      image: '/images/1a.jpg',
      price: 50,
      countInStock: 1,
      from: 'China',
      finish: 'Bone & Metal',
      rating: 5,
      numReviews: 1,
      description:
        'Handmade with metal, camel bone, and wood.  Asian snuff bottle, has makers mark on bottom.',
    },
    {
      _id: '2',
      name: 'Madonna and Child',
      slug: 'Madonna and Child',
      category: 'Religious',
      image: '/images/2a.jpg',
      price: 50,
      countInStock: 1,
      from: 'Italy',
      finish: 'Wood and Gold Leaf',
      rating: 5,
      numReviews: 1,
      description: 'Made in Italy, Madonna and Child wall plack unframed',
    },
    {
      _id: '3',
      name: 'Carved Wood Cup',
      slug: 'Carved Wood Cup',
      category: 'Asian',
      image: '/images/3a.jpg',
      price: 50,
      countInStock: 1,
      from: 'China',
      finish: 'Wood',
      rating: 5,
      numReviews: 1,
      description: 'From China, hand carved wood shaped like a cup.',
    },
    {
      _id: '4',
      name: 'Spiral Staircase',
      slug: 'Staircase',
      category: 'Wood',
      image: '/images/4a.jpg',
      price: 500,
      countInStock: 1,
      from: 'America',
      finish: 'Wood',
      rating: 5,
      numReviews: 1,
      description:
        'Hand made spiral staircase inspired by Sam Maloof staircase, Curly Maple base, Apitong wood stairs, spire, and 4 layer lamination handrail, made by Gabe Castro.',
    },
    {
      _id: '5',
      name: 'Jade Grapes',
      slug: 'Jade Grapes',
      category: 'Asian',
      image: '/images/5a.jpg',
      price: 100,
      countInStock: 1,
      from: 'China',
      finish: 'Jade',
      rating: 5,
      numReviews: 1,
      description: 'Mid Century Hand Carved Jade Grapes.',
    },
    {
      _id: '6',
      name: 'Terra Cotta Jug',
      slug: 'Terra Cotta Jug',
      category: 'Ceramic',
      image: '/images/6a.jpg',
      price: 100,
      countInStock: 1,
      from: 'Italy',
      finish: 'Glazed',
      rating: 5,
      numReviews: 1,
      description: 'Hand made in Italy Terra Cotta two handled jug.',
    },
    {
      _id: '7',
      name: 'Metal Asian Horse',
      slug: 'Horse',
      category: 'Metal',
      image: '/images/7a.jpg',
      price: 25,
      countInStock: 1,
      from: 'Japan',
      finish: 'Gold',
      rating: 5,
      numReviews: 1,
      description:
        'Hand painted Chinese Rose Medallion Decorative plate, makers mark on bottom.',
    },
    {
      _id: '8',
      name: 'Asian Nun',
      slug: 'Asian Nun',
      category: 'Religious',
      image: '/images/8a.jpg',
      price: 25,
      countInStock: 1,
      from: 'Japan',
      finish: 'Metal and Gold Leaf',
      rating: 5,
      numReviews: 1,
      description: 'Hand painted Japanese Nun, Metal and Gold Leaf.',
    },
    {
      _id: '9',
      name: 'Celadon Brush Pot',
      slug: 'Celadon Brush Pot',
      category: 'Asian',
      image: '/images/9a.jpg',
      price: 125,
      countInStock: 1,
      from: 'China',
      finish: 'Stone',
      rating: 5,
      numReviews: 1,
      description: 'Hand Carved Chinese Celadon Stone, Brush Pot.',
    },
    {
      _id: '10',
      name: 'Asian Clock',
      slug: 'Asian Clock',
      category: 'Clock',
      image: '/images/10a.jpg',
      price: 50,
      countInStock: 1,
      from: 'American',
      finish: 'Wood and Stencil',
      rating: 5,
      numReviews: 1,
      description:
        'Made in America, Asian inspired Quartz AA battery table top clock',
    },
    {
      _id: '11',
      name: 'Sandstone MudMan',
      slug: 'Sandstone MudMan',
      category: 'Asian',
      image: '/images/11a.jpg',
      price: 125,
      countInStock: 1,
      from: 'China',
      finish: 'Sandstone',
      rating: 5,
      numReviews: 1,
      description: 'Hand Carved Chinese Sandstone MudMan.',
    },

    {
      _id: '12',
      name: 'Wood Bowl Branch',
      slug: 'Bowl',
      category: 'Wood',
      image: '/images/12b.jpg',
      price: 250,
      countInStock: 1,
      from: 'American',
      finish: 'Wood',
      rating: 5,
      numReviews: 1,
      description:
        'Hand Made decorative art piece, Mesquite wood hand turned by Mark Jackofsky.',
    },
    {
      _id: '13',
      name: 'Asian Rice Container',
      slug: 'Container',
      category: 'Asian',
      image: '/images/13a.jpg',
      price: 300,
      countInStock: 1,
      from: 'China',
      finish: 'Painted Wood',
      rating: 5,
      numReviews: 1,
      description:
        'Large Chinese hand painted wooden rice container, 1930 era.',
    },
    {
      _id: '14',
      name: 'Pablo Picasso Print',
      slug: 'Art Print',
      category: 'Art',
      image: '/images/14a.jpg',
      price: 500,
      countInStock: 1,
      from: 'Spain',
      finish: 'Paper',
      rating: 5,
      numReviews: 1,
      description: 'La espara (Margot) Print by Pablo Picasso.',
    },
    {
      _id: '15',
      name: 'Alice Sweede Painting',
      slug: 'Art Painting',
      category: 'Art',
      image: '/images/15a.jpg',
      price: 300,
      countInStock: 1,
      from: 'American',
      finish: 'Oil on Canvas',
      rating: 5,
      numReviews: 1,
      description: 'Roses round painting done by Alice Sweede.',
    },
    {
      _id: '16',
      name: 'Granite Foot Stool',
      slug: 'Foot Stool',
      category: 'Asian',
      image: '/images/16a.jpg',
      price: 300,
      countInStock: 1,
      from: 'China',
      finish: 'Granite',
      rating: 5,
      numReviews: 1,
      description: 'Hand carved Granite Chinese foot stool.',
    },

    {
      _id: '17',
      name: 'Mantle Clock',
      slug: 'Mantle Clock',
      category: 'Clock',
      image: '/images/7a.jpg',
      price: 200,
      countInStock: 1,
      from: 'England',
      finish: 'Wood, Enamel',
      rating: 5,
      numReviews: 1,
      description:
        'English Mantle Clock, Turn of the century antique, work great.',
    },
    {
      _id: '18',
      name: 'Rose Medallion Plate',
      slug: 'Plate',
      category: 'Asian',
      image: '/images/18a.jpg',
      price: 100,
      countInStock: 1,
      from: 'China',
      finish: 'Ceramic',
      rating: 5,
      numReviews: 1,
      description:
        'Hand painted Chinese Rose Medallion Decorative plate, makers mark on bottom.',
    },
    {
      _id: '19',
      name: 'Pablo Picasso Dove Print',
      slug: 'Pablo Picasso Dove Print',
      category: 'Art',
      image: '/images/19a.jpg',
      price: 500,
      countInStock: 1,
      from: 'Spain',
      finish: 'Acrylic',
      rating: 5,
      numReviews: 1,
      description: 'Dove Print by Pablo Picasso.',
    },
    {
      _id: '20',
      name: 'Rose Medallion Vase',
      slug: 'Rose Medallion Vase',
      category: 'Asian',
      image: '/images/20a.jpg',
      price: 250,
      countInStock: 1,
      from: 'China',
      finish: 'Ceramic',
      rating: 5,
      numReviews: 1,
      description:
        'Hand painted Chinese Rose Medallion Decorative vase, makers mark on bottom.',
    },
  ],
};
export default data;
